/*
 * can-ids.h
 *
 *  Created on: 2020.04.29.
 *      Author: Szbuli
 */

#ifndef CAN_CAN_IDS_H_
#define CAN_CAN_IDS_H_

#define	RELAY_CONTROLLER_DEVICE_ID	100
#define	RELAY_CONTROLLER_SET_RELAY_1	101
#define	RELAY_CONTROLLER_SET_RELAY_2	102
#define	RELAY_CONTROLLER_SET_RELAY_3	103
#define	RELAY_CONTROLLER_SET_RELAY_4	104
#define	RELAY_CONTROLLER_SET_RELAY_5	105
#define	RELAY_CONTROLLER_CONFIGURE_TAMPER	117
#define	RELAY_CONTROLLER_TAMPER	118
#define	RELAY_CONTROLLER_HEARTBEAT	119
#define	RELAY_CONTROLLER_FACTORY_RESET	120
#define	RELAY_CONTROLLER_CONFIGURE_HEARTBEAT	121
#define	RELAY_CONTROLLER_HA_SENSOR_CONFIG	122

#endif /* CAN_CAN_IDS_H_ */
